spring:
  datasource:
    # mysql: com.mysql.cj.jdbc.Driver
    # mariadb: org.mariadb.jdbc.Driver
    driver-class-name: org.h2.Driver
    # mysql: jdbc:mysql://localhost:3306/testdb
    # mariadb: jdbc:mariadb://localhost:3306/testdb
    url: jdbc:h2:mem:testdb
    username: sa
    password: #비밀번호
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:sql/data.sql
      mode: always